# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-30 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='projectcategory',
            old_name='sub_categories',
            new_name='tasks',
        ),
        migrations.AddField(
            model_name='project',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iapi.ProjectTask'),
        ),
    ]
