# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-30 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iapi', '0002_auto_20160430_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltag',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
